#!/usr/bin/env python3
# Bake the Windows command icon atlas into a C++ byte array. Decoding is
# deferred to runtime via SDL3_image so the linked data stays compact.

import os
import sys


def write_bytes_array(lines, name, data, storage="static "):
    lines.append(f"{storage}const uint8_t {name}[{len(data)}] = {{")
    chunk = []
    for i, b in enumerate(data):
        chunk.append(f"0x{b:02x},")
        if (i + 1) % 16 == 0:
            lines.append("    " + " ".join(chunk))
            chunk = []
    if chunk:
        lines.append("    " + " ".join(chunk))
    lines.append("};")


def main(argv):
    if len(argv) < 3:
        sys.stderr.write("usage: bake_command_icons.py <out_dir> <png_path>\n")
        return 2

    out_dir = argv[1]
    png_path = argv[2]
    os.makedirs(out_dir, exist_ok=True)

    with open(png_path, "rb") as f:
        data = f.read()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError(f"{png_path}: not a PNG file")

    header_path = os.path.join(out_dir, "command_icons_data.h")
    hlines = [
        "// Auto-generated by tools/bake_command_icons.py - do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "extern const uint8_t kATCommandIconsPNGData[];",
        "extern const size_t kATCommandIconsPNGSize;",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    tmp = header_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("\n".join(hlines))
    os.replace(tmp, header_path)

    source_path = os.path.join(out_dir, "command_icons_data.cpp")
    slines = [
        "// Auto-generated by tools/bake_command_icons.py - do not edit.",
        '#include "command_icons_data.h"',
        "",
    ]
    write_bytes_array(slines, "kATCommandIconsPNGData", data, storage="")
    slines.extend([
        "",
        f"const size_t kATCommandIconsPNGSize = {len(data)};",
        "",
    ])
    tmp = source_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("\n".join(slines))
    os.replace(tmp, source_path)

    print(f"{os.path.basename(png_path)}: {len(data)} bytes")
    print(f"Wrote {header_path}")
    print(f"Wrote {source_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
