// AltirraBridgeServer — headless bridge server
//
// Minimal main loop that runs the Altirra emulator and serves the
// bridge protocol over a local socket. Speaks the same protocol as
// `AltirraSDL --bridge`, with no SDL3 main window, no Dear ImGui, no
// librashader, no display backend, no input layer, no UI tree.
//
// Linker dependencies (see CMakeLists.txt):
//   ATCPU, ATEmulation, ATDevices, ATIO, ATAudio, ATNetwork,
//   ATNetworkSockets, ATDebugger, ATVM, ATCore, Kasumi, vdjson,
//   system, plus the bridge module (source/bridge/*).
//
// SDL3 is NOT linked. The audio mixer (audiooutput_sdl3.cpp) is
// compiled with -DALTIRRA_AUDIO_NULL which stubs out every SDL call
// and returns a nullptr audio stream — samples generated by the full
// POKEY/mixer pipeline are silently discarded. Screenshot, rawscreen,
// and render_frame work exactly as in AltirraSDL: ATBridgeNullVideoDisplay
// (ui_stubs.cpp) is installed as GTIA's video output so mpLastFrame is
// populated at the end of each frame, and the bridge render commands
// pull XRGB8888 pixels via VDPixmapBlt and encode PNG with the vendored
// encoder in bridge_commands_render.cpp — none of which touches SDL3.

#include <stdafx.h>

#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <thread>

#include "simulator.h"
#include "gtia.h"
#include "bridge_logging.h"
#include "settings.h"            // ATSettingsCategory enum + ATSettingsLoadLastProfile
#include "constants.h"           // ATHardwareMode, ATMemoryMode enums
#include "debugger.h"            // ATGetDebugger() — for --debugbrkrun

#include "bridge_server.h"
#include <at/atcore/constants.h>
#include <vd2/VDDisplay/display.h>

// Forward declarations for AltirraSDL frontend symbols we re-use.
// These functions are defined in source/app/*.cpp / source/ui/core/*.cpp
// in the AltirraSDL frontend, but their bodies are platform-agnostic
// and pulled into the AltirraBridgeServer link via the explicit source
// list in CMakeLists.txt. We declare them at file scope (NOT inside an
// anonymous namespace) so the linker resolves them to the file-scope
// definitions in the AltirraSDL sources we link.
class ATDeviceManager;
class VDStringA;
extern VDStringA ATGetConfigDir();
extern void      ATRegistryLoadFromDisk();
extern void      ATInitSaveStateDeserializer();
extern void      ATVFSInstallAtfsHandler();
extern void      ATRegisterDevices(ATDeviceManager& dm);
extern void      ATRegisterDeviceXCmds(ATDeviceManager& dm);
extern bool      ATSocketInit();
extern void      ATLoadConfigVars();
extern void      ATOptionsLoad();
// Debugger engine init — required by Phase 5a commands (DISASM,
// CALLSTACK, EVAL) which go through ATGetDebugger()->GetTarget().
// ATDebugger registers the CPU as its default debug target during
// Init().
extern void      ATInitDebugger();
extern void      ATShutdownDebugger();
// ui_stubs.cpp — headless null video display so GTIA generates frames
// even though there's no real display backend. Required by SCREENSHOT
// et al.
class IVDVideoDisplay;
extern IVDVideoDisplay *ATBridgeCreateNullVideoDisplay();
extern bool ATBridgeNullVideoDisplayConsumeFramePosted(IVDVideoDisplay *display);
static IVDVideoDisplay *g_pNullDisplay = nullptr;
// ATLoadDefaultProfiles is declared in settings.h (which we include) as
// `bool ATLoadDefaultProfiles()` — no need to redeclare here.

// ATUIState is referenced by ATBridge::Poll's signature even though
// the bridge module doesn't dereference it. The header lives in the
// SDL3 frontend's source/ui/core/, which we deliberately do NOT
// include here — instead, declare a stub locally.
struct ATUIState {};

// =========================================================================
// Globals — kept minimal
// =========================================================================

ATSimulator g_sim;
static ATUIState g_uiState;
// g_running is intentionally NOT static — ui_stubs.cpp's
// ATBridgeRequestAppQuit() flips it from another TU when the bridge
// processes a QUIT command.
std::atomic<bool> g_running { true };

// =========================================================================
// Phase 3 deferred-action glue (synchronous direct-call versions)
//
// The bridge module's BOOT / MOUNT / STATE_SAVE / STATE_LOAD commands
// call these functions instead of going through the SDL3 deferred
// action queue. In headless mode the bridge IS the only event source,
// so we run the work synchronously between bridge polls.
//
// (NOTE: declared in bridge_main_glue.h. The SDL3 frontend provides a
// different implementation in bridge_main_glue_sdl3.cpp.)
// =========================================================================

#include "bridge_main_glue.h"
#include <vd2/system/file.h>
#include <vd2/system/text.h>
#include <vd2/system/VDString.h>
#include <vd2/system/error.h>
#include <at/atcore/media.h>
#include <at/atio/image.h>
#include "mediamanager.h"        // ATMediaLoadContext (full definition)
#include "firmwaremanager.h"

static const char *BridgeHardwareModeName(ATHardwareMode mode) {
	switch (mode) {
		case kATHardwareMode_800:    return "800";
		case kATHardwareMode_800XL:  return "800XL";
		case kATHardwareMode_1200XL: return "1200XL";
		case kATHardwareMode_130XE:  return "130XE";
		case kATHardwareMode_XEGS:   return "XEGS";
		case kATHardwareMode_1400XL: return "1400XL";
		case kATHardwareMode_5200:   return "5200";
		default:                     return "unknown";
	}
}

static void BridgeLogSimulatorConfig(const char *stage) {
	const uint32 profileId = ATSettingsGetCurrentProfileId();
	VDStringA profileName;
	try {
		profileName = VDTextWToU8(ATSettingsProfileGetName(profileId));
	} catch (...) {
		profileName = "";
	}

	ATFirmwareInfo kernelInfo {};
	ATFirmwareInfo basicInfo {};
	const bool haveKernelInfo = g_sim.GetFirmwareManager()
		&& g_sim.GetFirmwareManager()->GetFirmwareInfo(g_sim.GetActualKernelId(), kernelInfo);
	const bool haveBasicInfo = g_sim.GetFirmwareManager()
		&& g_sim.GetFirmwareManager()->GetFirmwareInfo(g_sim.GetActualBasicId(), basicInfo);

	VDStringA kernelName;
	VDStringA basicName;
	if (haveKernelInfo)
		kernelName = VDTextWToU8(kernelInfo.mName);
	if (haveBasicInfo)
		basicName = VDTextWToU8(basicInfo.mName);

	BRIDGE_LOG_INFO("BridgeServer",
		"%s config: profile=%08x '%s', machine=%s, memory=%u, "
		"basic=%s, video=%d, kernel_id=$%016llx actual_kernel=$%016llx '%s', "
		"basic_id=$%016llx actual_basic=$%016llx '%s'",
		stage,
		(unsigned)profileId,
		profileName.c_str(),
		BridgeHardwareModeName(g_sim.GetHardwareMode()),
		(unsigned)g_sim.GetMemoryMode(),
		g_sim.IsBASICEnabled() ? "on" : "off",
		(int)g_sim.GetVideoStandard(),
		(unsigned long long)g_sim.GetKernelId(),
		(unsigned long long)g_sim.GetActualKernelId(),
		kernelName.c_str(),
		(unsigned long long)g_sim.GetBasicId(),
		(unsigned long long)g_sim.GetActualBasicId(),
		basicName.c_str());
}

bool ATBridgeDispatchBoot(ATSimulator& sim, const std::string& path) {
	if (path.empty()) return false;
	try {
		ATMediaLoadContext ctx;
		const VDStringW wpath = VDTextU8ToW(VDStringSpanA(path.c_str()));
		ctx.mOriginalPath = wpath.c_str();
		ctx.mImageName = wpath.c_str();
		ctx.mWriteMode = kATMediaWriteMode_RW;
		if (!sim.Load(ctx)) {
			BRIDGE_LOG_ERROR("BridgeServer", "BOOT load failed: %s", path.c_str());
			return false;
		}
		// Match the SDL3 frontend behaviour: cold-reset after a
		// successful boot so the kernel finds the freshly-loaded
		// image. Preserve pause state per the CLAUDE.md invariant
		// (the bridge command itself only needs the boot to land;
		// running state is the client's choice).
		const bool wasPaused = sim.IsPaused();
		sim.ColdReset();
		if (wasPaused) sim.Pause(); else sim.Resume();
		return true;
	} catch (const MyError& e) {
		BRIDGE_LOG_ERROR("BridgeServer", "BOOT exception: %s", e.c_str());
		return false;
	}
}

bool ATBridgeDispatchMount(ATSimulator& sim, int drive, const std::string& path) {
	if (path.empty() || drive < 0 || drive > 14) return false;
	try {
		ATMediaLoadContext ctx;
		const VDStringW wpath = VDTextU8ToW(VDStringSpanA(path.c_str()));
		ctx.mOriginalPath = wpath.c_str();
		ctx.mImageName = wpath.c_str();
		ctx.mWriteMode = kATMediaWriteMode_RW;
		// MOUNT targets a specific drive — use the cart load context
		// to express it. Phase 1 of the headless build uses Load()
		// which dispatches by file type; an .atr image goes to a
		// disk drive selected by the loader. For drive-specific
		// mounting we'd need to call lower-level disk APIs; defer
		// to a follow-up if needed.
		(void)drive;
		if (!sim.Load(ctx)) {
			BRIDGE_LOG_ERROR("BridgeServer", "MOUNT load failed: %s", path.c_str());
			return false;
		}
		return true;
	} catch (const MyError& e) {
		BRIDGE_LOG_ERROR("BridgeServer", "MOUNT exception: %s", e.c_str());
		return false;
	}
}

bool ATBridgeDispatchStateSave(ATSimulator& sim, const std::string& path) {
	if (path.empty()) return false;
	try {
		const VDStringW wpath = VDTextU8ToW(VDStringSpanA(path.c_str()));
		sim.SaveState(wpath.c_str());
		return true;
	} catch (const MyError& e) {
		BRIDGE_LOG_ERROR("BridgeServer", "STATE_SAVE exception: %s", e.c_str());
		return false;
	}
}

bool ATBridgeDispatchStateLoad(ATSimulator& sim, const std::string& path) {
	if (path.empty()) return false;
	try {
		// sim.Load() auto-detects the savestate format (legacy
		// .altstate vs. .altstate2) by magic and routes through
		// LoadState / ApplySnapshot internally. The deserializer
		// registry is populated at startup by the
		// ATInitSaveStateDeserializer() call in main(). Pause
		// state is preserved per the CLAUDE.md invariant: clients
		// that want to resume after load issue RESUME explicitly.
		const VDStringW wpath = VDTextU8ToW(VDStringSpanA(path.c_str()));
		ATImageLoadContext ctx{};
		if (!sim.Load(wpath.c_str(), kATMediaWriteMode_RO, &ctx)) {
			BRIDGE_LOG_ERROR("BridgeServer", "STATE_LOAD failed: %s", path.c_str());
			return false;
		}
		return true;
	} catch (const MyError& e) {
		BRIDGE_LOG_ERROR("BridgeServer", "STATE_LOAD exception: %s", e.c_str());
		return false;
	}
}

// =========================================================================
// Signal handling
// =========================================================================

static void HandleSignal(int /*sig*/) {
	g_running.store(false);
}

// =========================================================================
// Argument parsing
// =========================================================================

namespace {
struct Args {
	std::string bridgeAddr = "tcp:127.0.0.1:0";
	bool        printHelp    = false;
	// CONFIG overrides (applied after settings load, before first ColdReset)
	bool        hasNoBasic   = false;
	std::string machine;             // empty = use settings default
	std::string memory;              // empty = use settings default
	bool        debugBrkRun  = false;
};

void PrintHelp() {
	std::fprintf(stderr,
		"AltirraBridgeServer — headless Altirra emulator + bridge server\n"
		"\n"
		"Usage: AltirraBridgeServer [options]\n"
		"\n"
		"Options:\n"
		"  --bridge[=ADDR]   Listen address for the bridge protocol.\n"
		"                    ADDR forms:\n"
		"                      tcp:127.0.0.1:PORT     loopback TCP (default if no spec)\n"
		"                      tcp                    same as tcp:127.0.0.1:0 (OS picks port)\n"
		"                      unix:/path/to/socket   POSIX filesystem UDS\n"
		"                      unix-abstract:NAME     Linux abstract namespace UDS\n"
		"                    Default: tcp:127.0.0.1:0\n"
		"  --no-basic          Disable built-in BASIC ROM.\n"
		"  --machine=MODE      Hardware mode: 800, 800XL, 1200XL, 130XE, XEGS,\n"
		"                        1400XL, 5200. Default: from settings.\n"
		"  --memory=SIZE       Memory size: 8K..1088K. Default: from settings.\n"
		"  --debugbrkrun       Enable break-on-EXE-run-address.\n"
		"  -h, --help          Show this help.\n"
		"\n"
		"On startup the server prints connection and diagnostic paths on stderr:\n"
		"  [Bridge] listening on tcp:127.0.0.1:54321\n"
		"  [Bridge] token-file: /tmp/altirra-bridge-12345.token\n"
		"  [Bridge] log-file: /tmp/altirra-bridge-12345.log\n"
		"\n"
		"Connect with the Python or C SDK from\n"
		"src/AltirraSDL/AltirraBridge/sdk/. The wire protocol is the\n"
		"same as `AltirraSDL --bridge`. See AltirraBridge/docs/PROTOCOL.md.\n"
		"\n"
		"Settings (kernel ROM paths, video standard, etc.) are read\n"
		"from ~/.config/altirra/settings.ini at startup, the same\n"
		"location used by AltirraSDL. The headless server does NOT\n"
		"write settings on exit.\n");
}

bool ParseArgs(int argc, char** argv, Args& out) {
	for (int i = 1; i < argc; ++i) {
		const char* a = argv[i];
		if (std::strcmp(a, "-h") == 0 || std::strcmp(a, "--help") == 0) {
			out.printHelp = true;
		} else if (std::strcmp(a, "--bridge") == 0) {
			out.bridgeAddr = "tcp:127.0.0.1:0";
		} else if (std::strncmp(a, "--bridge=", 9) == 0) {
			out.bridgeAddr = a + 9;
		} else if (std::strcmp(a, "--no-basic") == 0) {
			out.hasNoBasic = true;
		} else if (std::strncmp(a, "--machine=", 10) == 0) {
			out.machine = a + 10;
		} else if (std::strncmp(a, "--memory=", 9) == 0) {
			out.memory = a + 9;
		} else if (std::strcmp(a, "--debugbrkrun") == 0) {
			out.debugBrkRun = true;
		} else {
			std::fprintf(stderr, "AltirraBridgeServer: unknown argument: %s\n", a);
			return false;
		}
	}
	return true;
}
}  // namespace

// =========================================================================
// Simulator init
//
// This is a stripped-down version of main_sdl3.cpp's startup sequence,
// keeping only what's needed for the simulator to boot and run. We
// deliberately skip:
//   - Window/display creation
//   - ImGui init
//   - Joystick manager (the bridge does its own input injection)
//   - Touch / mobile UI
//   - Input maps (none of the SDL3 input layer is linked)
//   - Window placement
// =========================================================================

static bool InitSimulator() {
	// Use the same registry namespace as AltirraSDL so kernel ROM
	// paths and other settings are inherited from the user's GUI
	// configuration. The headless server does not write back.
	VDRegistryAppKey::setDefaultKey("AltirraSDL");

	BRIDGE_LOG_INFO("BridgeServer", "config dir = %s", ATGetConfigDir().c_str());
	ATRegistryLoadFromDisk();

	// Pre-simulator init matching main_sdl3.cpp.
	ATInitSaveStateDeserializer();
	ATVFSInstallAtfsHandler();

	BRIDGE_LOG_INFO("BridgeServer", "initialising simulator...");
	g_sim.Init();
	g_sim.SetRandomSeed((uint32)std::rand() ^ ((uint32)std::rand() << 15));
	g_sim.LoadROMs();

	// Install a null IVDVideoDisplay so GTIA actually generates
	// frames. With mpDisplay==nullptr, BeginFrame() bails out early
	// and mpLastFrame is never populated, breaking SCREENSHOT /
	// RAWSCREEN / RENDER_FRAME. The null display is a pure sink: it
	// hangs onto the frame ref for one VBI cycle so the frame
	// allocator can recycle it, and discards everything else.
	// FrameSkip MUST be true here: nothing in the bridge server's
	// main loop calls RevokeBuffer() on the null display, so with
	// FrameSkip=false GTIA would see GetQueuedFrames()>0 every tick
	// and stall the simulator waiting for display consumption. That
	// left the sim running at ~5% of real speed (~1400 cycles/frame
	// instead of ~29829), so client a.frame(N) calls never advanced
	// N real frames and games like river_raid never reached active
	// gameplay. Screenshots still work because they read
	// GTIA::mpLastFrame, which is populated regardless of whether
	// the display queue has been consumed.
	g_pNullDisplay = ATBridgeCreateNullVideoDisplay();
	g_sim.GetGTIA().SetVideoOutput(g_pNullDisplay);
	g_sim.GetGTIA().SetFrameSkip(true);

	ATRegisterDevices(*g_sim.GetDeviceManager());
	ATRegisterDeviceXCmds(*g_sim.GetDeviceManager());

	ATSocketInit();
	ATLoadConfigVars();
	ATOptionsLoad();

	const bool createdDefaultProfiles = ATLoadDefaultProfiles();
	if (createdDefaultProfiles)
		BRIDGE_LOG_INFO("BridgeServer", "created default profiles in settings store");
	// Load most settings categories. Skip:
	//   - FullScreen        (window placement, meaningless without a window)
	//   - Input / InputMaps (call into the joystick manager which is
	//                        nullptr in headless mode and would crash
	//                        in ATSettingsExchangeInput)
	ATSettingsLoadLastProfile((ATSettingsCategory)(
		kATSettingsCategory_All
		& ~kATSettingsCategory_FullScreen
		& ~kATSettingsCategory_Input
		& ~kATSettingsCategory_InputMaps
	));
	BridgeLogSimulatorConfig("loaded");

	// Initialize the debugger engine so Phase 5a commands
	// (DISASM / CALLSTACK / EVAL) have a valid debug target.
	ATInitDebugger();

	g_sim.ColdReset();
	g_sim.Resume();

	return true;
}

static std::chrono::steady_clock::duration BridgeGetFrameDuration() {
	double fps = kATFrameRate_NTSC;

	switch (g_sim.GetVideoStandard()) {
		case kATVideoStandard_SECAM:
			fps = kATFrameRate_SECAM;
			break;

		case kATVideoStandard_PAL:
		case kATVideoStandard_NTSC50:
			fps = kATFrameRate_PAL;
			break;

		case kATVideoStandard_NTSC:
		case kATVideoStandard_PAL60:
		default:
			fps = kATFrameRate_NTSC;
			break;
	}

	return std::chrono::duration_cast<std::chrono::steady_clock::duration>(
		std::chrono::duration<double>(1.0 / fps));
}

static void BridgePollUntil(std::chrono::steady_clock::time_point deadline) {
	using clock = std::chrono::steady_clock;
	constexpr auto pollTick = std::chrono::microseconds(500);

	for (;;) {
		const auto now = clock::now();
		if (now >= deadline)
			break;

		const auto tickDeadline = now + pollTick;
		std::this_thread::sleep_until(tickDeadline < deadline
			? tickDeadline
			: deadline);
		ATBridge::Poll(g_sim, g_uiState);
	}
}

// =========================================================================
// Main loop
// =========================================================================

int main(int argc, char** argv) {
	Args args;
	if (!ParseArgs(argc, argv, args)) return 2;
	if (args.printHelp) { PrintHelp(); return 0; }

	// Install signal handlers so Ctrl+C cleanly tears down the bridge.
	std::signal(SIGINT,  HandleSignal);
	std::signal(SIGTERM, HandleSignal);
#ifndef _WIN32
	std::signal(SIGPIPE, SIG_IGN);  // socket sends survive client disconnect
#endif

	ATBridgeLog::Init();
	BRIDGE_LOG_INFO("BridgeServer", "log-file: %s", ATBridgeLog::GetPath());

	if (!InitSimulator()) {
		std::fprintf(stderr, "AltirraBridgeServer: simulator init failed\n");
		ATBridgeLog::Shutdown();
		return 1;
	}

	// ---- Apply CLI overrides after settings load, before bridge ----
	{
		bool needReset = false;

		if (args.hasNoBasic) {
			g_sim.SetBASICEnabled(false);
			needReset = true;
		}

		if (!args.machine.empty()) {
			const char* m = args.machine.c_str();
			bool ok = true;
			if      (!strcasecmp(m, "800"))    g_sim.SetHardwareMode(kATHardwareMode_800);
			else if (!strcasecmp(m, "800xl"))   g_sim.SetHardwareMode(kATHardwareMode_800XL);
			else if (!strcasecmp(m, "1200xl"))  g_sim.SetHardwareMode(kATHardwareMode_1200XL);
			else if (!strcasecmp(m, "130xe"))   g_sim.SetHardwareMode(kATHardwareMode_130XE);
			else if (!strcasecmp(m, "xegs"))    g_sim.SetHardwareMode(kATHardwareMode_XEGS);
			else if (!strcasecmp(m, "1400xl"))  g_sim.SetHardwareMode(kATHardwareMode_1400XL);
			else if (!strcasecmp(m, "5200"))    g_sim.SetHardwareMode(kATHardwareMode_5200);
			else { std::fprintf(stderr, "AltirraBridgeServer: unknown --machine: %s\n", m); ok = false; }
			if (!ok) return 2;
			needReset = true;
		}

		if (!args.memory.empty()) {
			const char* m = args.memory.c_str();
			bool ok = true;
			if      (!strcasecmp(m, "8k"))    g_sim.SetMemoryMode(kATMemoryMode_8K);
			else if (!strcasecmp(m, "16k"))   g_sim.SetMemoryMode(kATMemoryMode_16K);
			else if (!strcasecmp(m, "24k"))   g_sim.SetMemoryMode(kATMemoryMode_24K);
			else if (!strcasecmp(m, "32k"))   g_sim.SetMemoryMode(kATMemoryMode_32K);
			else if (!strcasecmp(m, "40k"))   g_sim.SetMemoryMode(kATMemoryMode_40K);
			else if (!strcasecmp(m, "48k"))   g_sim.SetMemoryMode(kATMemoryMode_48K);
			else if (!strcasecmp(m, "52k"))   g_sim.SetMemoryMode(kATMemoryMode_52K);
			else if (!strcasecmp(m, "64k"))   g_sim.SetMemoryMode(kATMemoryMode_64K);
			else if (!strcasecmp(m, "128k"))  g_sim.SetMemoryMode(kATMemoryMode_128K);
			else if (!strcasecmp(m, "256k"))  g_sim.SetMemoryMode(kATMemoryMode_256K);
			else if (!strcasecmp(m, "320k"))  g_sim.SetMemoryMode(kATMemoryMode_320K);
			else if (!strcasecmp(m, "576k"))  g_sim.SetMemoryMode(kATMemoryMode_576K);
			else if (!strcasecmp(m, "1088k")) g_sim.SetMemoryMode(kATMemoryMode_1088K);
			else { std::fprintf(stderr, "AltirraBridgeServer: unknown --memory: %s\n", m); ok = false; }
			if (!ok) return 2;
			needReset = true;
		}

		if (args.debugBrkRun)
			ATGetDebugger()->SetBreakOnEXERunAddrEnabled(true);

		if (needReset) {
			g_sim.ColdReset();
			g_sim.Resume();
		}
		BridgeLogSimulatorConfig("effective");
	}

	if (!ATBridge::Init(args.bridgeAddr)) {
		std::fprintf(stderr, "AltirraBridgeServer: bridge init failed\n");
		ATBridgeLog::Shutdown();
		return 1;
	}

	BRIDGE_LOG_INFO("BridgeServer", "entering main loop");

	// The simulator's Advance() runs one bounded scanline chunk, not
	// one video frame. Pace only at the actual GTIA frame boundary
	// reported by the null display; otherwise FRAME N runs about
	// 9-10x too slow because each partial chunk gets a full-frame
	// sleep. While waiting for a frame deadline, poll the bridge in
	// short ticks so free-running clients still get low-latency
	// responses.
	using clock = std::chrono::steady_clock;
	auto nextFrameDeadline = clock::now() + BridgeGetFrameDuration();

	while (g_running.load()) {
		// 1. Process bridge commands (non-blocking, capped at 64
		//    commands/poll).
		ATBridge::Poll(g_sim, g_uiState);

		// 2. Tick the simulator until a real frame is produced or
		//    the simulator stops. With SetFrameSkip(true), GTIA
		//    should not block waiting for display consumption.
		ATSimulator::AdvanceResult result = ATSimulator::kAdvanceResult_Running;
		bool framePosted = false;

		while (g_running.load()) {
			result = g_sim.Advance(false);

			if (ATBridgeNullVideoDisplayConsumeFramePosted(g_pNullDisplay)) {
				framePosted = true;
				break;
			}

			if (result == ATSimulator::kAdvanceResult_Stopped
				|| result == ATSimulator::kAdvanceResult_WaitingForFrame)
				break;
		}

		// 3. Pace once per produced frame. For a frame-gated run,
		//    keep the gate active during the sleep so the client's
		//    next command remains queued until the documented
		//    wall-clock frame has elapsed. For free-running frames,
		//    notify before sleeping so a FRAME command received
		//    during the wait starts counting from the next frame.
		if (framePosted) {
			const bool frameGateWasActive = ATBridge::IsFrameGateActive();

			if (!frameGateWasActive)
				ATBridge::OnFrameCompleted(g_sim);

			auto now = clock::now();
			if (now >= nextFrameDeadline)
				nextFrameDeadline = now;
			else
				BridgePollUntil(nextFrameDeadline);

			nextFrameDeadline += BridgeGetFrameDuration();

			if (frameGateWasActive)
				ATBridge::OnFrameCompleted(g_sim);
		}

		// 4. When paused, poll on a short sub-tick so command
		//    round-trips do not wait for a full frame.
		if (result == ATSimulator::kAdvanceResult_Stopped) {
			std::this_thread::sleep_for(std::chrono::microseconds(500));
			nextFrameDeadline = clock::now() + BridgeGetFrameDuration();
		} else if (result == ATSimulator::kAdvanceResult_WaitingForFrame && !framePosted) {
			std::this_thread::sleep_for(std::chrono::microseconds(500));
			nextFrameDeadline = clock::now() + BridgeGetFrameDuration();
		}
	}

	BRIDGE_LOG_INFO("BridgeServer", "shutting down");

	ATBridge::Shutdown(g_sim);
	ATShutdownDebugger();

	g_sim.GetGTIA().SetVideoOutput(nullptr);
	if (g_pNullDisplay) {
		g_pNullDisplay->Destroy();
		g_pNullDisplay = nullptr;
	}
	g_sim.Shutdown();

	return 0;
}
